"""
    xpuFP

A laboratory for the number representations that accelerator hardware actually uses:
fixed point, the IEEE-style floating-point zoo down to four bits, the block-scaled
microscaling formats (MXFP4, NVFP4), the redundant systems inside every multiplier
(CSD, Booth, redundant radix 4, carry-save), and the error analysis that decides
between them.

Every format is implemented from the bit pattern up — encode, decode, round,
saturate — so the arithmetic can be *watched* rather than trusted, and every figure
in the accompanying documentation is generated by the package itself.

# Organisation

| Layer        | What it provides                                                     |
|:-------------|:---------------------------------------------------------------------|
| Formats      | [`FloatFormat`](@ref), [`FixedFormat`](@ref), [`BlockFormat`](@ref)  |
| Arithmetic   | [`fpadd`](@ref), [`fpmul`](@ref), [`fpdiv`](@ref), [`fpfma`](@ref) — each returning a full datapath trace |
| Blocks       | [`quantize_block`](@ref), [`block_dot`](@ref), [`block_gemm`](@ref)  |
| Redundant    | [`csd`](@ref), [`booth_radix4`](@ref), [`rr4_add`](@ref), [`wallace_reduce`](@ref) |
| Analysis     | [`snr_db`](@ref), [`effective_bits`](@ref), [`element_snr`](@ref), [`dot_snr`](@ref) |
| Illustration | `plot_*` functions, all CairoMakie                                    |

See the documentation for the guided tour.
"""
module xpuFP

using Printf
using Random
using Statistics
using LinearAlgebra
using QuadGK
using SpecialFunctions
using CairoMakie

# ---- formats ---------------------------------------------------------------
export FloatFormat, FixedFormat, NaNStyle, ZeroExponent, OverflowMode
export IEEE_NAN, E4M3_NAN, E8M0_NAN, NO_SPECIAL
export SUBNORMAL_ZERO, NORMAL_ZERO, SATURATE, WRAP, THROW
export FP64, FP32, FP16, BF16, E5M2, E4M3, E2M1, E1M2, E3M0, E8M0
export ALL_FLOAT_FORMATS, FP4_FAMILY
export nbits, emin, emax, maxfinite, minnormal, minsubnormal, machine_eps
export dynamic_range, decimal_digits, max_normal_E, nexpcodes, nmancodes
export encode, decode, quantize, grid, posgrid, midpoints, ulp
export resolution, fxmax, fxmin, fxrange, imax, imin

# ---- arithmetic ------------------------------------------------------------
export FPParts, Stage, DatapathTrace, unpack, binade_exponent
export fpadd, fpsub, fpmul, fpdiv, fpfma, fpmul_then_add
export fadd, fmul, fdiv, ffma, relerror, rounding_ulps
export fxadd, fxsub, fxmul, fxdiv, fxdot
export seq_sum, tree_sum, kahan_sum, fp_dot
export stagnation_trace, stagnation_threshold

# ---- blocks ----------------------------------------------------------------
export IntFormat, INT4, INT8, ElementFormat, intmin
export DigitFormat, RR4, RR4_MAX, CSD, SIGNED_BINARY, BINARY, RADIX4
export ALL_DIGIT_FORMATS, alphabet, to_digits, conforms, radix_parts
export BlockFormat, ScaleRule, QuantizedBlock, BlockDotResult
export MX_FLOOR_POW2, NV_MAXDIV, BEST_POW2, MSE_OPTIMAL, OPT_SHIFT
export MXFP4, NVFP4, MXINT4, ALL_BLOCK_FORMATS
export elem_emax, bits_per_element, bits_per_block, block_scale
export quantize_block, quantize_blocked, dequantize, reconstruct
export dead_zone_threshold, good_zone_threshold, zeroed_count
export needs_tensor_scale, tensor_scale
export block_dot, block_gemm, core_sum_bound, scale_fixup_overhead
export storage_bytes, compression_ratio
export MXFP4_BEST32, MXFP4_BEST16, NVFP4_BEST16, XPFP4_32, XPFP4_16
export MXFP4_OPT32, MXFP4_OPT16, PHISTAR, opt_shift_threshold
export mx_scale_opt, opt_shift_fires, opt_shift_rate
export IMPROVED_BLOCK_FORMATS, hadamard, RotatedBlockFormat, rotated
export BlockSchemeReport, compare_block_schemes, print_scheme_table
export test_distributions, SchemeMetrics, measure_scheme, benchmark_schemes
export print_benchmark, dot_snr_curve, error_profile, pareto_frontier
export SNRSimulation, simulate_snr, analytic_snr, estimate_element_snr
export grid_distance, dot_snr_law
export GridLUT, gridlut, lut_quantize, BlockKernel, blockkernel
export QuickSNR, quick_snr, quick_data, quick_compare, quick_sweep, fp4_variant

# ---- analysis --------------------------------------------------------------
export DB_PER_BIT, LOG_UNIFORM_INV_SQ
export snr_db, effective_bits, rel_rms_error, cosine_similarity, cosine_from_snr
export quantize_all, measure_snr, per_element_relerror
export db_per_bit, resolution_fraction, predicted_snr

# ---- redundant number systems ----------------------------------------------
export SignedDigits, value, weight, adders, ndigits_sd, digit_string
export is_redundant, redundancy, has_adjacent_nonzeros
export to_binary, twos_complement_bits, twos_complement_value, to_radix
export csd, naf, csd_trace, binary_weight, all_signed_spellings
export verify_csd_minimal, min_signed_weight, csd_multiplier_taps, csd_multiply, csd_density
export RR4Alphabet, MAX_REDUNDANT, MIN_REDUNDANT, alphabet_halfwidth
export dyadic_parts, to_rr4_minimal, to_rr4_maximal
export max_representable, min_ndigits, minimal_rr4
export all_rr4_representations, count_rr4_representations
export rr4_representation_counts, rr4_branch_residues, rr4_max_count
export minimal_weight, weight_distribution, WeightStats, weight_stats, weight_scaling
export canonical_rr4, nonadjacent_rr4, has_nonadjacent_form
export RR4Representations, RR4Complexity, rr4_representations, rr4_complexity
export digit_matrix, digit_matrix_with_scale
export rr4_with_length, rr4_rescale
export float_value, scale, nfracdigits, isintegral
export scaled_integer, digit_parts, to_rr4_parts, to_digits_parts
export promote_alphabet, same_spelling, sum_rr4, dot_rr4
export RR4Column, RR4AddTrace, to_rr4, rr4_transfer, rr4_transfer_minimal
export rr4_add, rr4_split_table, conventional_add_trace, ripple_depth
export absorption_table, verify_absorption, verify_minimal_closure
export verify_sign_coupling, verify_rr4_random, spelling_census
export booth_radix2, booth_radix4, booth_radix4_unsigned, BoothProduct
export booth_multiply, booth_rows, verify_booth_exhaustive
export booth_pairing, booth_borrow_form
export csa, verify_csa_identity, ReductionTrace, wallace_reduce, dadda_reduce
export dadda_targets, reduction_schedule, compressor_cells
export verify_tree_invariant, booth_tree_saving

# ---- conversions -----------------------------------------------------------
export convert_format, narrow, int_to_float, float_to_fixed, fixed_to_float
export nextafter, prevafter, encodings_monotone, top_seam, bottom_seam
export to_carrysave, from_carrysave, rr4_to_canonical
export minimal_to_maximal, maximal_to_minimal
export ExcursionClass, INVISIBLE, VISIBLE_BETTER, VISIBLE_WORSE
export Excursion, excursion, multiplier_excursion
export redundant_dot_excursion, mx_excursion
export AnyFormat, realvalue, represent, ConversionReport
export conversion_report, conversion_matrix

# ---- arithmetic algorithms -------------------------------------------------
export AddResult, MultiplyResult
export serial_add, parallel_prefix_add, carry_free_add, carry_save_add, compare_adders
export shift_add_multiply, wallace_multiply, booth_wallace_multiply
export csd_constant_multiply, rr4_multiply, compare_multipliers
export rr4_recode, rr4_recode_table, AccumulatorRun, accumulator_inputs
export accumulate_rr4, accumulate_carry, compare_accumulators, accumulator_scaling
export CostBudget, RR4_BITS_PER_DIGIT, BINARY_BITS_PER_RADIX4_DIGIT
export add_costs, accumulate_costs, multiply_costs, constant_multiply_costs
export cost_report, format_memory_costs
export mxfp4_widths, sign_detect_depth, mxfp4_multiply_options
export mxfp4_reduction_options, mxfp4_dot_costs, mxfp4_softmax_costs, rr4_opportunity
export CycleBudget, DEFAULT_LEVELS_PER_CYCLE, cycles_for, add_cycles, multiply_cycles
export accumulate_cycles, dot_cycles, softmax_cycles, clock_sensitivity, cycle_report
export FO4_PER_LEVEL, fo4_range, float_multiply_stages, float_multiply_depth
export PipeStage, Pipe, pipeline_plan, pipeline_cut, pipeline_time, pipeline_speedup
export pipeline_utilization, pipeline_breakeven, pipeline_timeline, pipeline_report
export float_multiply_pipeline
export MulRung, one_cycle_multiply, one_cycle_clock, one_cycle_report, one_cycle_formats
export HLSDecl, hls_types, hls_accumulator_bits, HLS_CONTROL, hls_operator_table
export ENERGY_WEIGHTS, hls_energy, hls_energy_compare, hls_pragmas, hls_report

# ---- hardware --------------------------------------------------------------
export SystolicRun, systolic_run, systolic_cycles, systolic_utilization
export systolic_start_cycle

# ---- illustration ----------------------------------------------------------
export xpufp_theme, savefig, format_color, blank_axis, text_on, LIGHTSKYBLUE
export _fmtname
export SIGN_COLOR, EXP_COLOR, FRAC_COLOR, INT_COLOR, GREY, ACCENT, ACCENT2
export bitcell!, bitrun!, brace!, labelbox!, arrow!
export plot_digit_layout, plot_layout_comparison, plot_rr4_representations
export plot_weight_scaling
export plot_bit_layout, plot_format_zoo, plot_fp4_codes, plot_mx_block_layout
export plot_number_line, plot_binade_spacing, plot_edges_map, plot_seams
export plot_log_axis_analogy
export plot_relative_error, plot_verdict_curve, plot_stagnation, plot_fp4_error_regimes
export plot_csd_digits, plot_csd_census, plot_booth_windows
export plot_rr4_addition, plot_absorption_table, plot_minimal_maps
export plot_dependency_graph, plot_factor_graph, plot_butterfly_vs_planes
export plot_wallace_tree, plot_reduction_pyramids
export plot_format_snr, plot_dot_snr_vs_length, plot_block_size_sweep
export plot_outlier_law, plot_energy_bars, plot_systolic_activity
export plot_block_schemes
export plot_xpfp4_pipeline, plot_rotation_effect
export plot_scale_placement, plot_block_reconstruction, plot_opt_shift
export plot_scheme_pareto, plot_benchmark_grid, plot_dot_snr_schemes
export plot_error_profiles, plot_block_snr_distribution, plot_snr_simulation


# ---------------------------------------------------------------------------
# Include order is a dependency order: a name used in a *type annotation* must
# already exist when the method is defined, even though names used inside function
# bodies resolve later.
# ---------------------------------------------------------------------------
include("formats/floatformat.jl")
include("formats/registry.jl")
include("formats/fixedpoint.jl")
include("formats/intformat.jl")

include("arith/datapath.jl")
include("arith/floatarith.jl")
include("arith/fixedarith.jl")
include("arith/summation.jl")

include("blocks/blockformat.jl")
include("blocks/blockarith.jl")
include("blocks/optshift.jl")
include("blocks/improved.jl")
include("analysis/benchmark.jl")
include("analysis/snrsim.jl")
include("analysis/snr.jl")
include("analysis/quicksim.jl")

include("redundant/signeddigit.jl")
include("redundant/csd.jl")
include("formats/digitformat.jl")     # needs SignedDigits and csd
include("redundant/rr4.jl")           # needs radix_parts
include("redundant/sdarith.jl")
include("redundant/weights.jl")
include("redundant/booth.jl")
include("redundant/carrysave.jl")
include("arith/algorithms.jl")        # needs RR4Alphabet in its signatures
include("arith/accumulator.jl")       # needs SignedDigits, rr4_add, to_rr4

include("analysis/costmodel.jl")      # needs booth_rows, compressor_cells, csd, formats
include("analysis/mxfp4cost.jl")      # needs the above plus grid/reduction_schedule
include("analysis/cyclemodel.jl")     # needs both depth models; only divides by a clock
include("analysis/hls.jl")            # needs mxfp4_widths and the multiply/reduction options
include("analysis/pipeline.jl")       # needs float_multiply_stages and cycles_for

include("convert/conversions.jl")
include("convert/universal.jl")
include("hardware/systolic.jl")

include("viz/theme.jl")
include("viz/bitlayout.jl")
include("viz/digitlayout.jl")
include("viz/numberline.jl")
include("viz/errorplots.jl")
include("viz/redundantviz.jl")
include("viz/graphviz.jl")
include("viz/snrplots.jl")
include("viz/xpfp4viz.jl")
include("viz/benchviz.jl")

end # module
